services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: repuestosdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm start"
    environment:
      PORT: 4000
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: repuestosdb
      DB_USER: admin
      DB_PASS: admin123
      JWT_SECRET: "d8f3a2c1b0e6f9a7d4c2b5e8f1a3c6d9b2e5f8a1c4d7e0f3a6b9c2d5e8f1a4b7e0f3"
      CORS_ORIGIN: "http://localhost:3000"
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Volumen anónimo para node_modules (MEJORA DE PERFORMANCE)
    command: sh -c "npm install && npm start"
    environment:
      - REACT_APP_API_URL=http://localhost:4000/api
      - CHOKIDAR_USEPOLLING=false  # Desactiva polling (más rápido)
      - WATCHPACK_POLLING=false    # Desactiva polling de watchpack
      - FAST_REFRESH=true          # Hot reload más rápido
      - WDS_SOCKET_PORT=3000       # Puerto para websocket del hot reload
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: